-- MySQL Script generated by MySQL Workbench
-- Sat Jun  9 15:50:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_gerenciamentodealuno
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_gerenciamentodealuno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_gerenciamentodealuno` DEFAULT CHARACTER SET utf8 ;
USE `db_gerenciamentodealuno` ;

-- -----------------------------------------------------
-- Table `db_gerenciamentodealuno`.`tbldepartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentodealuno`.`tbldepartamento` (
  `idDepartamento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_gerenciamentodealuno`.`tblcurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentodealuno`.`tblcurso` (
  `idCurso` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `idDepartamento`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_tblCurso_tblDepartamento1_idx` (`idDepartamento` ASC),
  CONSTRAINT `fk_tblCurso_tblDepartamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `db_gerenciamentodealuno`.`tbldepartamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_gerenciamentodealuno`.`tblaluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentodealuno`.`tblaluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(13) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idAluno`, `idCurso`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_tblAluno_tblCurso1_idx` (`idCurso` ASC),
  CONSTRAINT `fk_tblAluno_tblCurso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `db_gerenciamentodealuno`.`tblcurso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_gerenciamentodealuno`.`tbldisciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentodealuno`.`tbldisciplina` (
  `idDisciplina` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_gerenciamentodealuno`.`tblrequisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentodealuno`.`tblrequisitos` (
  `idtblrequisitos` INT NOT NULL,
  `requisitosDisciplina` INT NULL,
  `idDisciplina` INT NOT NULL,
  PRIMARY KEY (`idtblrequisitos`, `idDisciplina`),
  INDEX `fk_tblrequisitos_tbldisciplina1_idx` (`idDisciplina` ASC),
  CONSTRAINT `fk_tblrequisitos_tbldisciplina1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `db_gerenciamentodealuno`.`tbldisciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_gerenciamentodealuno`.`tblstatusad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentodealuno`.`tblstatusad` (
  `idStatusAD` INT NOT NULL AUTO_INCREMENT COMMENT '*final do nome da tabela |\nA - Aluno |\nD - Disciplina',
  `status` ENUM('M', 'C', 'P') NULL DEFAULT NULL COMMENT 'M - Matriculado |\nC - Concluido |\nP - Pendente',
  `idAluno` INT NOT NULL,
  `idDisciplina` INT NOT NULL,
  PRIMARY KEY (`idStatusAD`, `idAluno`, `idDisciplina`),
  INDEX `fk_tblStatusAD_tblAluno1_idx` (`idAluno` ASC),
  INDEX `fk_tblStatusAD_tblDisciplina1_idx` (`idDisciplina` ASC),
  CONSTRAINT `fk_tblStatusAD_tblAluno1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `db_gerenciamentodealuno`.`tblaluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblStatusAD_tblDisciplina1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `db_gerenciamentodealuno`.`tbldisciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_gerenciamentodealuno`.`tblstatuscd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentodealuno`.`tblstatuscd` (
  `idStatusCD` INT NOT NULL AUTO_INCREMENT COMMENT '*final do nome da tabela |\nC - Curso |\nD - Disciplina',
  `status` ENUM('O', 'L') NULL DEFAULT NULL COMMENT 'O - Obrigatorio |\nL - Livre (OPTATIVA)',
  `idDisciplina` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idStatusCD`, `idDisciplina`, `idCurso`),
  INDEX `fk_tem_tblDisciplina1_idx` (`idDisciplina` ASC),
  INDEX `fk_tem_tblCurso1_idx` (`idCurso` ASC),
  CONSTRAINT `fk_tem_tblCurso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `db_gerenciamentodealuno`.`tblcurso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tem_tblDisciplina1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `db_gerenciamentodealuno`.`tbldisciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_gerenciamentodealuno`.`tblusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentodealuno`.`tblusuario` (
  `idUsuario` INT NOT NULL COMMENT 'usuarios que podem ter acesso ao sistema',
  `nome` VARCHAR(45) NOT NULL,
  `perfil` VARCHAR(5) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `login_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
