-- MySQL Script generated by MySQL Workbench
-- Fri Jun  8 00:08:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_gerenciamentoDeAluno
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_gerenciamentoDeAluno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_gerenciamentoDeAluno` DEFAULT CHARACTER SET utf8 ;
USE `db_gerenciamentoDeAluno` ;

-- -----------------------------------------------------
-- Table `db_gerenciamentoDeAluno`.`tblDepartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentoDeAluno`.`tblDepartamento` (
  `idDepartamento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciamentoDeAluno`.`tblCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentoDeAluno`.`tblCurso` (
  `idCurso` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `idDepartamento`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_tblCurso_tblDepartamento1_idx` (`idDepartamento` ASC),
  CONSTRAINT `fk_tblCurso_tblDepartamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `db_gerenciamentoDeAluno`.`tblDepartamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciamentoDeAluno`.`tblEndereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentoDeAluno`.`tblEndereco` (
  `idEndereco` INT NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(5) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cep` INT NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciamentoDeAluno`.`tblAluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentoDeAluno`.`tblAluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(13) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `idCurso` INT NOT NULL,
  `idEndereco` INT NOT NULL,
  PRIMARY KEY (`idAluno`, `idCurso`, `idEndereco`),
  INDEX `fk_tblAluno_tblCurso1_idx` (`idCurso` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_tblAluno_tblEndereco1_idx` (`idEndereco` ASC),
  CONSTRAINT `fk_tblAluno_tblCurso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `db_gerenciamentoDeAluno`.`tblCurso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblAluno_tblEndereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `db_gerenciamentoDeAluno`.`tblEndereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciamentoDeAluno`.`tblDisciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentoDeAluno`.`tblDisciplina` (
  `idDisciplina` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciamentoDeAluno`.`tblStatusCD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentoDeAluno`.`tblStatusCD` (
  `idStatusCD` INT NOT NULL AUTO_INCREMENT COMMENT '*final do nome da tabela |\nC - Curso |\nD - Disciplina',
  `status` ENUM('O', 'L') NULL COMMENT 'O - Obrigatorio |\nL - Livre (OPTATIVA)',
  `idDisciplina` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idStatusCD`, `idDisciplina`, `idCurso`),
  INDEX `fk_tem_tblDisciplina1_idx` (`idDisciplina` ASC),
  INDEX `fk_tem_tblCurso1_idx` (`idCurso` ASC),
  CONSTRAINT `fk_tem_tblDisciplina1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `db_gerenciamentoDeAluno`.`tblDisciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tem_tblCurso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `db_gerenciamentoDeAluno`.`tblCurso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciamentoDeAluno`.`tblUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentoDeAluno`.`tblUsuario` (
  `idUsuario` INT NOT NULL COMMENT 'usuarios que podem ter acesso ao sistema',
  `nome` VARCHAR(45) NOT NULL,
  `perfil` VARCHAR(5) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `login_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciamentoDeAluno`.`tblStatusAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentoDeAluno`.`tblStatusAD` (
  `idStatusAD` INT NOT NULL AUTO_INCREMENT COMMENT '*final do nome da tabela |\nA - Aluno |\nD - Disciplina',
  `status` ENUM('M', 'C', 'P') NULL COMMENT 'M - Matriculado |\nC - Concluido |\nP - Pendente',
  `idAluno` INT NOT NULL,
  `idDisciplina` INT NOT NULL,
  PRIMARY KEY (`idStatusAD`, `idAluno`, `idDisciplina`),
  INDEX `fk_tblStatusAD_tblAluno1_idx` (`idAluno` ASC),
  INDEX `fk_tblStatusAD_tblDisciplina1_idx` (`idDisciplina` ASC),
  CONSTRAINT `fk_tblStatusAD_tblAluno1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `db_gerenciamentoDeAluno`.`tblAluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblStatusAD_tblDisciplina1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `db_gerenciamentoDeAluno`.`tblDisciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciamentoDeAluno`.`tblRequisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentoDeAluno`.`tblRequisitos` (
  `idRequisitos` INT NOT NULL,
  `requisitosDisciplina` INT NULL,
  `idDisciplina` INT NOT NULL,
  PRIMARY KEY (`idRequisitos`, `idDisciplina`),
  INDEX `fk_tblRequisitos_tblDisciplina1_idx` (`idDisciplina` ASC),
  CONSTRAINT `fk_tblRequisitos_tblDisciplina1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `db_gerenciamentoDeAluno`.`tblDisciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciamentoDeAluno`.`tblTelefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciamentoDeAluno`.`tblTelefone` (
  `idTelefone` INT NOT NULL,
  `telefoneFixo` VARCHAR(30) NULL,
  `telefoneCelular` VARCHAR(30) NULL,
  `idAluno` INT NOT NULL,
  PRIMARY KEY (`idTelefone`, `idAluno`),
  INDEX `fk_tblTelefone_tblAluno1_idx` (`idAluno` ASC),
  CONSTRAINT `fk_tblTelefone_tblAluno1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `db_gerenciamentoDeAluno`.`tblAluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
